// Generated by CoffeeScript 2.4.1
(function() {
  var Modules;

  Modules = {
    debugmodule: require("./debugmodule.js"),
    deleteprocessmodule: require("./deleteprocessmodule.js"),
    deletioninquirermodule: require("./deletioninquirermodule.js"),
    githubhandlermodule: require("./githubhandlermodule.js"),
    startupmodule: require("./startupmodule.js")
  };

  module.exports = Modules;

}).call(this);
