// Generated by CoffeeScript 2.4.1
(function() {
  var deleteprocessmodule, deletionInquirer, github, log;

  deleteprocessmodule = {
    name: "deleteprocessmodule"
  };

  //log Switch
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["deleteprocessmodule"] != null) {
      console.log("[deleteprocessmodule]: " + arg);
    }
  };

  //region internal variables
  github = null;

  deletionInquirer = null;

  //endregion

  //#initialization function  -> is automatically being called!  ONLY RELY ON DOM AND VARIABLES!! NO PLUGINS NO OHTER INITIALIZATIONS!!
  deleteprocessmodule.initialize = function() {
    log("deleteprocessmodule.initialize");
    github = allModules.githubhandlermodule;
    return deletionInquirer = allModules.deletioninquirermodule;
  };

  //region internal functions
  //endregion

  //region exposed functions
  deleteprocessmodule.execute = async function() {
    var reposToDelete;
    await github.buildConnection();
    reposToDelete = (await deletionInquirer.doUserInquiry());
    await github.deleteReposForUser(reposToDelete);
    return true;
  };

  //endregion
  module.exports = deleteprocessmodule;

}).call(this);
