// Generated by CoffeeScript 2.4.1
(function() {
  var chalk, clear, deleteProcess, figlet, log, printBanner, startupmodule;

  startupmodule = {
    name: "startupmodule"
  };

  //region node_modules
  chalk = require('chalk');

  clear = require('clear');

  figlet = require('figlet');

  //endregion

  //log Switch
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["startupmodule"] != null) {
      console.log("[startupmodule]: " + arg);
    }
  };

  //region internal variables
  deleteProcess = null;

  //endregion

  //#initialization function  -> is automatically being called!  ONLY RELY ON DOM AND VARIABLES!! NO PLUGINS NO OHTER INITIALIZATIONS!!
  startupmodule.initialize = function() {
    log("startupmodule.initialize");
    return deleteProcess = allModules.deleteprocessmodule;
  };

  //region internal functions
  printBanner = function() {
    clear();
    console.log(chalk.green(figlet.textSync("Delete", {
      horizontalLayout: 'full'
    })));
    return console.log(chalk.green(figlet.textSync("Repos", {
      horizontalLayout: 'full'
    })));
  };

  //endregion

  //region exposed functions
  startupmodule.cliStartup = async function() {
    var done, err;
    log("startupmodule.cliStartup");
    printBanner();
    try {
      done = (await deleteProcess.execute());
      if (done) {
        return console.log(chalk.green('All done!\n'));
      }
    } catch (error) {
      err = error;
      console.log(chalk.red('Error!'));
      console.log(err);
      return console.log("\n");
    }
  };

  //endregion exposed functions
  module.exports = startupmodule;

}).call(this);
